---
title: "R Notebook"
output: html_notebook
---

# Lodaing Packages
```{r}
library(xts)
library(forcats)
library(forecast)
library(ggplot2)
library(MASS)
```


# Loading dataset

```{r}
data <-read.csv("C:/Users/Simone/Documents/Desktop/Time_Series_Forecasting_Prediction/data2022_train.csv")
data
```

```{r}
#Cambio formato data
data <- xts(data$y, as.POSIXct(data$X, format="%Y-%m-%d %H:%M:%S", tz="GMT"))
head(data)
```

# Data Exploration

```{r}
#frequenza con cui i dati sono registrati nel tempo
periodicity(data)
```

```{r}
summary(data)
```
```{r}
#Check valori nulli
any(is.na(data))
```

```{r}
# Grafico dei dati originali
plot(data)

# Grafico dei dati settimanali con legenda
plot(apply.weekly(data, FUN = mean), main = "Dati settimanali")
legend("topright", legend = "Dati settimanali", lty = 1, col = "black")

# Grafico dei dati mensili con legenda
plot(apply.monthly(data, FUN = mean), main = "Dati mensili")
legend("topright", legend = "Dati mensili", lty = 1, col = "black")
```
```{r}
# crea l'oggetto "msts" e la decomposizione STL
msts_cons <- data[1:(144*60)] |> msts(seasonal.periods = c(144, 144*7))
comp_dec <- msts_cons |> mstl() |> autoplot()

# aggiungi una legenda
comp_dec <- comp_dec + labs(title = "Decomposizione STL") +
  scale_color_manual(values = c("blue", "red", "green", "black"),
                     name = "Componenti",
                     labels = c("Serie originale", "Trend", "Stagionalità giornaliera (144)", "Stagionalità settimanale (1008)"))
comp_dec <- comp_dec + labs(color = "Componenti", title = "Decomposizione STL")
comp_dec
```

```{r}
# Grafico dei dati orari con legenda
plot(data[1:144], main = "Dati orari")
legend("topright", legend = "Dati orari", lty = 1, col = "black")

# Grafico dei dati settimanali  con legenda
plot(data[1:144*21], main = "Dati settiminali")
legend("topright", legend = "Dati giornalieri", lty = 1, col = "black")

# Grafico dei dati settimanali con legenda
weekly <- autoplot(data[1:144*7]) + xlab('Giorni') + ylab('Power')
weekly + labs(title = "Dati settimanali") +
  theme(plot.title = element_text(hjust = 0.5)) +
  theme(axis.title = element_text(size = 10)) +
  theme(axis.text = element_text(size = 8))
legend("topright", legend = "Dati settimanali", lty = 1, col = "black")
```


```{r}
# Controllo varianza stazionaria
med <- tapply(data, rep(1:334, each = 144), mean)
sds <- tapply(data, rep(1:334, each = 144), sd)
plot(med, sds, main = "Scatterplot media e deviazione standard")
```



```{r}
BoxCox.lambda(data, "loglik")

bc <- boxcox(sds ~ med)
lambda <- bc$x[which.max(bc$y)]
lambda
```

